//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doctor()
        {
            this.doctor_schedule = new HashSet<doctor_schedule>();
        }
    
        public long id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string mobile_number { get; set; }
        public string national_code { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public long room_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doctor_schedule> doctor_schedule { get; set; }
        public virtual room room { get; set; }
    }
}
