//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor_schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doctor_schedule()
        {
            this.visits = new HashSet<visit>();
        }
    
        public long id { get; set; }
        public long doctor_id { get; set; }
        public long schedule_id { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual schedule_of_on_call schedule_of_on_call { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visit> visits { get; set; }
    }
}
