//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class medical_records
    {
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime infection_date { get; set; }
        public Nullable<System.DateTime> recovery_date { get; set; }
        public long patient_id { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
