//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalEntities : DbContext
    {
        public HospitalEntities()
            : base("name=HospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<doctor_schedule> doctor_schedule { get; set; }
        public virtual DbSet<doctor> doctors { get; set; }
        public virtual DbSet<medical_records> medical_records { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<schedule_of_on_call> schedule_of_on_call { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<visit> visits { get; set; }
    }
}
