//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit
    {
        public long id { get; set; }
        public long doctor_schedule_id { get; set; }
        public long patient_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual doctor_schedule doctor_schedule { get; set; }
        public virtual patient patient { get; set; }
    }
}
